# codacy configuration file

---

engines:
    coverage:
        enabled: true
        exclude_paths: [
            'tests',
        ]
    pylint:
        enabled: true
        python_version: 3

exclude_paths: [
    'backend/**',
    'diag_scripts/**',
    'interface_data/**',
    'interface_scripts/**',
    'main.py',
    'nml/**',
    'plot_scripts/**',
    'reformat_scripts/**',
    'variable_defs/**',
]
