---
name: esmvaltool
channels:
  - conda-forge
  - esmvalgroup

dependencies:
  # Python packages that cannot be installed from PyPI:
  - gdal
  - esmvalcore>=2.0.0b9,<2.1
  # Non-Python dependencies
  - graphviz
  - cdo>=1.9.7
  - imagemagick
  - nco
  - scikit-learn  # install from same installer as scipy; see issue ESMValTool: 1610

  # Multi language support:
  - python>=3.6
  - ncl
  - r-base
  - r-curl  # Dependency of lintr, but fails to compile because it cannot find libcurl installed from conda.
  - r-udunits2  # Fails to compile because it cannot find udunits2 installed from conda.
