---

name: esmvaltool
channels:
- conda-forge
#- defaults # in case of missing packages
#- Clyde_Fare #for scientific python

# ESMVALTOOL DEPENDENCIES

dependencies:
# Needed by main, preprocessor, workflow, one or more diagnostics, shared diagnostic code.
- basemap
- cartopy
- cf_units
- cython
- esgf-pyclient
- flask
- iris
- ncl
- netcdf4
- numba
- numpy
- pillow # providing PIL package
- python-cdo
- python-stratify
- pyyaml
- scipy
- shapely
- six
#- scientificpython

# Old Iris and ncl dependency block. Simply using the top level packages should be enough now.
# iris
#- iris
#- cartopy=0.15.*
#- matplotlib=1.5.*
#
#- ncl
#- hdf4=4.2.12
#- hdf5=1.8.17
#- icu=58.1
#- libnetcdf=4.4.1.1
#- xorg-libsm=1.2.2
#- xorg-libxext
#- xorg-libxrender

# DEVELOPMENT DEPENDENCIES
#
# Dependencies below that are required by 'setup.py test' and 'setup.py lint'
# should also be automatically be installed by setup.py in a temporary
# location when required to run the command.

# documentation
- sphinx

# testing
- easytest
- mock
- nose
- pytest
- pytest-cov
- pytest-html

# Note that there can be only one pip section
- pip:
  # TODO: replace geoval by conda package and move to ESMVALTOOL DEPENDENCIES
  - geoval
  # TODO: replace dummydata by conda/PyPI package and move to testing
  - "--editable=git+https://github.com/esmvalgroup/dummydata.git#egg=dummydata-dev"
  # code style (pip versions are more up to date)
  - isort
  - prospector[with_pyroma]
  - pycodestyle  # also used for testing
  - pydocstyle
  - pylint
  - yapf
