version: 2
jobs:
  build:
    working_directory: /esmvaltool
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          # Add some system packages (mostly since geoval needs them)
          command: |
            apt-get update -y && apt-get install -y build-essential
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          # Update/Create Conda Environment
          command: |
            if ! test -d "/opt/conda/envs/esmvaltool2"; then conda create -y -n esmvaltool2 python=2; fi
            if ! test -d "/opt/conda/envs/esmvaltool3"; then conda create -y -n esmvaltool3 python=3; fi 
            conda env update --quiet --file environment.yml --name esmvaltool2
            conda env update --quiet --file environment.yml --name esmvaltool3
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "environment.yml" }}
          paths:
            - "/opt/conda/envs/esmvaltool2"
            - "/opt/conda/envs/esmvaltool3"
      - run:
          # Activate Conda environment and run tests
          command: |
            source activate esmvaltool3
            ./setup.py test
            source activate esmvaltool2
            ./setup.py test
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/
      - run:
          # Upload Python 3 test coverage to codacy, even when the actual
          # running of the tests fails.
          when: always
          command: |
            pip install codacy-coverage
            python-codacy-coverage -r test-reports/python3/coverage.xml
