# User's configuration file for the ESMValTool
---

write_plots: true
write_netcdf: true
log_level: info
exit_on_warning: false
output_file_type: ps

output_dir: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/test_output/

save_intermediary_cubes: false

rootpath:
  CMIP5: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/testdata
  OBS: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/testdata
  default: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/testdata

drs:
  CMIP5: BADC
